### ISSUE TITLE
VS 2017 is crashing after todays update

### ISSUE THREAD

**Issue by 7mPx** [poma/MinimalisticView#12] opened 2019-04-06 15:11 UTC
The title says it all.
Can I get a crashreport somewhere from VS?

**Comment by poma** [comment] 2019-04-06 15:16
Does it display anything or the window silently disappears?

**Comment by 7mPx** [comment] 2019-04-06 15:19
The window just disappears

**Comment by poma** [comment] 2019-04-06 15:41
This is most likely caused by dependency update in latest commits. Try starting Visual Studio with logging enabled https://docs.microsoft.com/en-us/visualstudio/ide/reference/log-devenv-exe?view=vs-2019

**Comment by poma** [comment] 2019-04-06 15:44
Looks like I got Threading dependency wrong. I'll try to compile test version while you are looking for logs

**Comment by 7mPx** [comment] 2019-04-06 16:01
So i got a created log file without extension and the ActivityLog.xls in the attached zip

[log.zip](https://github.com/poma/MinimalisticView/files/3050663/log.zip)

**Comment by wzhymxz** [comment] 2019-04-07 06:29
How do I not open the vs2017 disable control

**Comment by poma** [comment] 2019-04-07 06:32
You can temporarily remove the extension from `AppData/Local/Microsoft/VisualStudio/2017/Extensions`

**Comment by fyc132** [comment] 2019-04-07 07:01
After updating today ,vs2017 Black Screen.

**Comment by poma** [comment] 2019-04-07 07:30
Temporarily reverted latest commits and uploaded as a new version until this problem is solved

**Comment by cg31** [comment] 2019-04-07 08:27
Maybe FeedbackPanel meends a null check before using? On VS2017, it could be null.

**Comment by poma** [comment] 2019-04-07 17:14
Oh snap, I did this check but accidentally removed it during refactoring. You might be right.

**Comment by machinechina** [comment] 2019-04-08 07:40
Also on  VS2019 , it crashs on startup window.
But RIGHT-click VS icon and select a recent solution works.

**Comment by theparticleman** [comment] 2019-04-16 21:26
I just found this extension after installing VS2019 today. It is now officially my new favorite extension. If you need help testing it when you re-enable 2019 support, please let me know. I'm running both 2017 and 2019 and would love it to work in both.

**Comment by poma** [comment] 2019-07-31 15:28
Fixed in #14

**Closed by poma** 2019-07-31 15:28 UTC
